UTDNebula/nebula-api

api/controllers/degree.ts
api/routes/degree.ts
api/server.ts

Resolves #36 
The changes in this pull request add a simple POST endpoint for degrees to insert them into the database. 
The changes are:
1. Add express.json() middleware to read request json objects
2. Add a POST endpoint for degrees that directly inputs information from json body

Add POST degree/insert

---

docs/schemas/academic_session.md
docs/schemas/assistant.md
docs/schemas/course.md
docs/schemas/degree.md
docs/schemas/exam.md
docs/schemas/location.md
docs/schemas/meeting.md
docs/schemas/professor.md
docs/schemas/requirement.md
docs/schemas/section.md

This PR copies the schema from the discussions to the repository.

Schema Documentation

---

api/models/course.ts
api/models/degree.ts

The updates typescript definitions and mongoDB schemas to match the newly designed schemas for the currently existing models.
The changes are:
1. Course schemas have been updated
2. Degree schemas have been updated

update schemas to match newly designed schemas

---

docs/schemas/degree.md

Degrees can vary across years so it would be useful to be able to support multiple years of degrees.

Add `year` field

---

api/controllers/professor.ts
api/models/professor.ts
api/routes/professor.ts
api/server.ts

Has a dependency in PR https://github.com/UTDNebula/nebula-api/pull/68

Add /professor endpoints

---

api/models/course.ts
api/models/professor.ts
api/models/section.ts

This pull request should make the professor/section/course models more in line with the layout of the data currently in the DB and closer to the real data representation. The same model layouts are already in use in the code of the scraper fork.

FIX: Fix professor/section/course models

---

docs/schemas/credit.md
docs/schemas/exam.md

Here are my proposed changes to the exam schema. Please let me know what you think, especially with the new Credit type.

Exam Schema Changes

---

scraper/data/Exams.json
scraper/data/ExamsWithoutObjectIds.json

Replaced examReference with exam_reference in Exam data to match schema design.

exam_reference fix

---

scraper/data/Exams.json
scraper/data/ExamsWithoutObjectIds.json

Replaced minimumscore with minimum_score in Exam data to match schema design.

minimum_score fix

---

docs/index.md

I have updated the documentation per issue #112.

Update server documentation

---

api/configs/env.go
api/configs/setup.go
api/controllers/course.go
api/controllers/degree.go
api/controllers/exam.go
api/controllers/professor.go
api/controllers/section.go

Issue #125
Establishes limit/offset pagination. Limit can be specified in .env and offset can be specified in query. Default value for limit is 20 and offset is 0. Limit/offset was applied to:
- Section/Professor/Degree/Exam/Section...Search()
- ExamAll()

REST API Pagination

---

api/go.mod
api/go.sum
api/server.go

Enables CORS for Planner, and other frontend solutions.

Enable CORS

---

api/controllers/section.go

This hopefully fixes the professors query parameter in the sections endpoint. It is untested because my local environment didn't cooperate. I would like for someone else to test if it works.

Fixes the professors query parameter in the sections endpoint

---

api/configs/env.go
api/server.go

Clean up server.go and formalized how we handle environmental variables to allow non-critical variables to not be defined

Clean Up / ENV Handling

---

.gitignore
api/Dockerfile
api/Makefile
api/configs/env.go
api/configs/setup.go
api/controllers/course.go
api/controllers/degree.go
api/controllers/exam.go
api/controllers/professor.go
api/controllers/section.go
docs/index.md

In the PR:
1. Added a multi-stage docker file. This should drastically reduce the size of the docker image, allowing for a smaller attack surface for bugs.
2. Added a Makefile to make it easy to build the API with and without docker, as well as adding linter checks.
3. Fixed the issues pointed out by the linter in our code.
4. Documented building and testing in docs/index.md (please let me know if this is the right place, or if I should change it)

Multi-stage dockerfile and Makefile

---

api/configs/env.go
api/configs/setup.go

Go vet highlighted this issue. We should discuss adding go vet and other code linters to CI/CD, or at least check them before we merge PRs.

fixed logging statements

---

api/controllers/course.go
api/controllers/degree.go
api/controllers/professor.go
api/controllers/section.go
api/schema/objects.go

Implemented schema models for Course, Degree, Professor, and Section. Cleaned up schema/objects.go formatting

Implemented schema models, formatting cleanup

---

api/common/log/log.go
api/common/log/mongo_writer.go
api/configs/env.go
api/configs/setup.go
api/controllers/course.go
api/controllers/degree.go
api/controllers/exam.go
api/controllers/professor.go
api/controllers/section.go
api/go.mod
api/go.sum
api/server.go

Added the zerolog package to log to stdout in a structured JSON format.
Output contains severity level (Debug, Info, Error, or Panic)
Also has timestamp, file name, function name (fn), and line number.

Logging to stdout in JSON

---

api/controllers/course.go
api/schema/objects.go
api/schema/requirements.go

Closes #191 
Just needed to change a type to coerce it into the right format. Also added a fix for the ObjectID not being decoded correctly by the driver.

Fix unmarshalling for courses

---

api/controllers/course.go
api/controllers/degree.go
api/controllers/exam.go
api/controllers/grades.go
api/controllers/professor.go
api/controllers/section.go
api/responses/course_response.go
api/responses/degree_response.go
api/responses/error_response.go
api/responses/exam_response.go
api/responses/professor_response.go
api/responses/section_response.go

Courses, Degrees, Exams, Professors, and Sections now all have Multi and Single strongly-typed responses, and are used in their respective controllers. Additionally added an Error response for returning general error responses

Made response object data strongly-typed

---

api/schema/objects.go

These schemas match the data format in https://github.com/UTDNebula/nebula-api/pull/247

Add schemas for Astra data

---

api/schema/objects.go

Simple event type just like for Asta and Coursebook

Add mazevo event type

---

api/controllers/grades.go
api/routes/grades.go

My last attempt to make the code for section-type endpoint more consistent. Also, changing `semester/section_type` to `semester/sectionType` as @TyHil suggested. Thank you.

Minor fix on the section-type endpoint for Trends

---

api/controllers/rooms.go

Update the docs to correctly describe the rooms route as showing rooms from CourseBook, Astra, and Mazevo.

Update documentation for rooms view change

---

api/docs/docs.go
api/docs/swagger.yaml
api/schema/objects.go

About to update the view in MongoDB, this should match.

Update schema for room capacity info

---

api/schema/autocomplete_objects.go

So Trends can develop a way to include course names in its search.
Once merged I'll change the aggregation pipeline in MongoDB to
```
[
{
$lookup: {
from: "sections",
localField: "sections",
foreignField: "_id",
as: "section"
}
},
{
$unwind: {
path: "$section",
preserveNullAndEmptyArrays: true
}
},
{
$lookup: {
from: "professors",
localField: "section.professors",
foreignField: "_id",
as: "professor"
}
},
{
$unwind: {
path: "$professor",
preserveNullAndEmptyArrays: true
}
},
{
$project: {
course_number: "$course_number",
title: "$title",
"academic_session.name":
"$section.academic_session.name",
section_number: "$section.section_number",
professor: {
first_name: "$professor.first_name",
last_name: "$professor.last_name"
},
subject_prefix: "$subject_prefix"
}
},
{
$group: {
_id: { …
```

Add course title to autocomplete endpoint for use in Trends

---

api/schema/objects.go

For https://github.com/UTDNebula/api-tools/pull/70

Schema update for api-tools map scraper

---

README.md

Related to https://github.com/UTDNebula/nebula-api/issues/288. It's not comprehensive, but will hopefully help new members get started. Let me know any suggestions.

Add Build, Contribute, and Run instructions to README.md
