UTDNebula/nebula-api

api/controllers/token.ts, api/models/token.ts, api/server.ts
Resolves #28 
The changes in this pull request add basic token functionality to add more control and security to the API. Token creation and customization are currently limited to being made directly in MongoDB.
The changes are:
1. Add middleware that checks for an Authorization HTTP header and compares it to tokens' objectId
2. Add tokenDB to the MongoDB development cluster 
3. Add schema for an API token
Future implementations related to this:
1. Implement API Token Rate Limiting #30 
2. Implement API Token Permissions and Authorization #29
=> Add basic token middleware

docs/schemas/professor.md
This is important to easily aggregate grade data for professors over time. This coupled with a new endpoint(s) should satisfy Athena's requirements.
=> Add `sections` field

docs/schemas/professor.md
Since professors can have multiple titles, we need to support this in our schema. This is not an edge case, it's fairly common. For examples, see Stephanie Adams and Thomas Butts on UTD Profiles.
=> Change `title` field to `titles` field

docs/schemas/professor.md
It is very to easy scrape a link to the professor's image. As such, I thought we should add it to the schema.
=> Add `image_uri` field

docs/schemas/degree.md
I noticed looking at all degrees at UT Dallas that there are many prescribed double majors (i.e. Bachelor of Science in Healthcare Management and Molecular Biology (Double Major)) with individualized degree plans. It is necessary to have a separate degree subtype to represent these.
I also noticed that all the degrees are nicely sorted by school and it would be easy to scrape them; Hence, the `school` field.
=> Add `DegreeSubtype` and `school` field

docs/schemas/section.md
The current schema has no field for specifying core requirements that a section meets, which was one of the requirements of the schema. This should fix that.
=> Add `core_flags` field

docs/schemas/section.md
Accidentally forgot to add `core_flags` field to the top of the section doc to go with #74
=> Properly list `core_flags` field in docs

docs/schemas/degree.md
I thought it might be useful to store the link to the degree in the catalog since we do that for professors already. I already have the links to each degree in the process of scraping so it takes no work to add this data in.
=> Add `catalog_uri` property

docs/schemas/degree.md
Added `certificate` and `track` degree subtypes as options. This is since there are quite a few certificates offered such as the Certificate in Information Assurance. In addition, the Bachelors of Arts in Education degree has several tracks one can take to specialize in teaching a certain area. These new subtypes cover these cases I've spotted while working on the degrees scraper.
=> Add `DegreeSubtype`s

docs/schemas/requirement.md
These new requirement types have already been implemented into the requisite parser on my branch and help to better describe some common requisites that courses have. I am open to adjusting them if need be, but I think they're fairly ready to go.
=> FEAT: Add new requirement types

api/models/course.ts, api/models/exam.ts, api/models/professor.ts, api/models/section.ts
Some of the models have been switched to use the combinedDB as aggregation only works when collections are within the same database.
Some of the models have been updated to have the _id string and some missing values.
=> Update models and redirect some to combinedDB

scraper/data/Exams.json, scraper/data/ExamsWithoutObjectIds.json, scraper/data/courses.json, scraper/scripts/BuildExamCourseAssociations.ts
This is the resulting data from scrapping from the UT Dallas Exam sites for IP, AP, CLEP, and ALEKS, per #66.
This will need to be incorporated to the database deployments as seen fit.
This is mostly done by hand as I haven't had internet access to develop and debug the scraper. I hope to have that finished before 3/28/2022, but depending on our priorities may have to push that further down the road.
=> Add Exam Data

docs/index.md, docs/schemas/academic_session.md, docs/schemas/assistant.md, docs/schemas/course.md, docs/schemas/credit.md, docs/schemas/degree.md, docs/schemas/exam.md, docs/schemas/location.md, docs/schemas/meeting.md, docs/schemas/professor.md, docs/schemas/requirement.md, docs/schemas/section.md
Improves docs formatting style:
- Blank lines around headers
- Blank lines around code blocks
- Backticks around strings (most have been changed)
- Escape <> tags after `Array`s (previously they were treated as HTML tags, causing them to be rendered as invisible)
- `Example` -> `Examples` if we're listing more than one example
- Remove trailing spaces at ends of lines
Also, fixes up the examples of certain fields like the dates/times and removes examples that don't exist in the database (e.g., most online-referring examples). Additionally, adds a note to the Meeting.modality field indicating there are currently no entries in the database that have that field populated.
Potentially related to #180.
=> Docs improvements

api/configs/setup.go, api/controllers/course.go, api/controllers/degree.go, api/controllers/evaluation.go, api/controllers/exam.go, api/controllers/professor.go, api/controllers/section.go
This is my attempt at making the DB instance a singleton pattern. 
The GetCollection function calls ConnectDB everytime its invoked - but the sync package's once.do should prevent from any more instances being created and just return the client from what I understood of documentation. I hope this does the job, if not please let me know what I can change/improve!
=> Implement singleton pattern for MongoDB instance

api/controllers/autocomplete.go, api/controllers/course.go, api/controllers/degree.go, api/controllers/exam.go, api/controllers/grades.go, api/controllers/professor.go, api/controllers/section.go, api/routes/autocomplete.go, api/routes/course.go, api/routes/degree.go, api/routes/exam.go, api/routes/grades.go, api/routes/professor.go, api/routes/section.go
Hi! I managed to totally simplify the controller functions now, including ```GradesAggregation()```. 
Thank you!
=> simplify the controller functions (totally)

api/controllers/course.go, api/controllers/professor.go, api/docs/docs.go
… the system to gather the data in time, and that 30s wasnt outrageously long time. Please let me know if I completed the task properly or if there should be any more changes thanks.
=> Change "All" Endpoint Timeouts #224

api/configs/setup.go, api/controllers/course.go, api/controllers/professor.go, api/routes/course.go, api/routes/professor.go
Hi! 
I've added the course endpoints in the professor's routes that return the array of courses taught by the queried professors (or single professor). I basically just filter the professors first and then, through several stages of the aggregation pipelines, sort of efficiently obtain the list of distinct courses by those professors. 
Let me know ASAP if there's anything I need to fix. 
Thank you.
=> Add courses aggregate endpoint to professor endpoint

api/controllers/course.go, api/controllers/professor.go, api/controllers/section.go
=> Add pagination documentation for /course /professor and /section

api/docs/docs.go, api/docs/swagger.yaml, api/schema/objects.go
I'll change the aggregation pipeline like so, adding the last 4 stages, after merge:
```
[
{
$project: {
buildings: 1
}
},
{
$unionWith: {
coll: "mazevo"
}
},
{
$unwind: "$buildings"
},
{
$unwind: "$buildings.rooms"
},
{
$project: {
building: "$buildings.building",
room: "$buildings.rooms.room",
capacity: null
}
},
{
$unionWith: {
coll: "astra",
pipeline: [
{
$unwind: "$buildings"
},
{
$unwind: "$buildings.rooms"
},
{
$project: {
building: "$buildings.building",
room: "$buildings.rooms.room",
capacity: {
$first:
"$buildings.rooms.events.capacity"
}
}
}
]
}
},
{
$group: {
_id: {
building: "$building",
room: "$room"
},
capacity: {
$max: "$capacity"
}
}
},
{
$group: {
_id: "$_id.building",
rooms: {
$push: {
room: "$_id.room",
capacity: "$capacity"
}
}
}
},
{
$project: {
_id: 0,
building: …
```
=> Add latitude and longitude to rooms type

api/controllers/storage.go, api/docs/docs.go, api/docs/swagger.yaml, api/routes/storage.go
added a new endpoint `/storage/:bucket/:objectID/url` for creating Signed URLs to be used for uploading files or limited downloads. accepts options for expiration time and headers so that projects can set for example, expiration time, MIME type, max content length, etc.
This also removes the ACL set when using PostObject,  letting either bucket level ACLs or Uniform Bucket Level policies control default behavior. if needed projects can use headers on Signed URLs to set ACL policies.
=> add new Signed URL endpoint
